---
- hosts: all
  pre_tasks:
    - block:
        - setup:
            gather_subset:
            - min
        - set_fact:
            ansible_python_interpreter: 'python3'
      tags: ['always']

  gather_facts: false
  roles:
    - {role: init, become: yes}
